# Generated by Django 4.2.20 on 2025-05-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sps_generics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_information", models.CharField(max_length=50)),
                ("reason", models.TextField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sps_generics.address",
                    ),
                ),
            ],
        ),
    ]
